FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
        ffmpeg \
        curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY merge_transcript.py summarize_transcript.py entrypoint.sh kafka_service.py check_health_services.py config.py ./
COPY model ./model
RUN chmod +x entrypoint.sh

ENTRYPOINT ["python3", "kafka_service.py"]
